---
title: "Twitter data processing"
author: "Yalin Yang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: TRUE
    toc_float: TRUE
  word_document:
    toc: no
    toc_depth: '3'
---

# 1. Load data

```{r message=FALSE, warning=FALSE}
# helper pacakge
library(wordcloud);library(tidytext);library(RColorBrewer);library(chron)
library(dplyr);library(ggplot2)
```

Use $UTF-8$ to decoding the data from twitter, and since '\n' would be treated as a line break in csv, so please use `read.table` in here.
```{r}
file = 'covid19.csv'
df <- read.table(file, header = TRUE, sep = ";", quote = "\"", dec = ".", fill = TRUE,encoding = 'UTF-8',stringsAsFactors = FALSE)
```

view the dataset

```{r}
head(df,10)
```

# 2. Visualization

## Tweets

```{r fig.height=8, fig.width=12, message=FALSE, warning=FALSE}
tweets_words <-  df %>%
 select(text) %>%
 unnest_tokens(word, text)
words <- tweets_words %>% count(word, sort=TRUE)

wordcloud(words = words$word, freq = words$n, 
          min.freq = 30,max.words=200, random.order=FALSE, rot.per=0.35,colors=brewer.pal(8, "Dark2"))
```

## Retweets

```{r}
summary(df$retweets)
(rt_lst <- table(df$retweets[!is.na(df$retweets)]))
```

```{r fig.height=6, fig.width=12}

barplot(rt_lst[2:length(rt_lst)], las = 2, 
        names.arg = names(rt_lst[2:length(rt_lst)]),
        col ="lightblue", main ="Frequncy of retweets",
        ylab = "Frequncy")
```

## Time-series

```{r}
frequncy_lst <- table(df$date)
df_time <- as.data.frame(frequncy_lst)[-1,]
df_time$date <- as.POSIXct(strptime(as.character(df_time$Var1),format ='%Y-%m-%d %H:%M'))
head(df_time)
```

```{r fig.height=8, fig.width=12, message=FALSE, warning=FALSE}
p <- ggplot(df_time, aes(x=date, y=as.numeric(Freq))) +
  geom_line()
p
```

